### ISSUE TITLE
issue unzip

### ISSUE THREAD

**Issue by robertoamoreno** [adventice/census#1]
Traceback (most recent call last):
  File "cli.py", line 120, in <module>
    unzip()
  File "cli.py", line 47, in unzip
    call(['7za', 'x', zipfile, '-y', '-o%s' % dest])
  File "/Users/admin/anaconda2/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/Users/admin/anaconda2/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/Users/admin/anaconda2/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by samueltc** [comment]
Thanks for reporting that issue!

You need to manually install `7za`.

I'm about to push major changes to the etl. You should wait these changes.

**Comment by samueltc** [comment]
You can have a look at merged PR #2 

I removed 7zip dependency. Please make sure you have UnZip 6.00.

Your feedback is much appreciated!

**Comment by robertoamoreno** [comment]
Awesome that worked on the latest =). One step missing in the ReadMe is create geo Database
